<div id="nav-top">
  <div class="container">
  <a href="#none">
    <?php
      echo $this->tag->image(
        array(
          "img/logo.png",
          "alt" => "expshell",
          "class" => "logo"
        )
      );
    ?>
  </a>
  <input type="text" placeholder="Search command"></input>
  <a href="#none">
    <?php
      echo $this->tag->image(
        array(
          "img/search.png",
          "alt" => "expshell",
          "class" => "search"
        )
      );
    ?>
  </a>
  </div>
</div>
<input id="save-commands" type="button" value="save commands"></input>
<button value="view saved commands">view saved commands</button>
